### ISSUE TITLE
Code block created in a table mode

### ISSUE THREAD

**Issue by masaiful** [lyon0xd/pelican-pixel#1]
Hi,

Thanks for this nice theme for Pelican. I am trying on my new site and there is some strange behavior regarding using code block.

If the code block starts with `#!`, e.g: `#!/bin/sh` the code block is automagically inside a table. While other codes are fine. (image below)

<img width="739" alt="image" src="https://user-images.githubusercontent.com/43263643/45540406-a90b2b80-b80c-11e8-9879-2ab3c8f532ad.png">

Do you know why this happens? And how do I prevent this to happen? I am a newbie and not sure about this behavior.

Thanks

**Comment by Asagizora** [comment]
Hi masaiful,

I'll try to find out the reason latter. 
For now, maybe the markdown code block syntax helps.

```

    ``` sh
    #!/bin/sh
    while read local_ref local_sha remote_ref remote_sha
    do
            if [ "$remote_ref" = "refs/heads/src" ]
            then
                    echo 'pushing output folder to master...'
                    pelican content -o output -s publishconf.py
                    ghp-import -b master -p output
            fi
    done
    ```

```

**Comment by masaiful** [comment]
Indeed it is. Thanks for the help
